version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    
  mailhog:
    image: mailhog/mailhog
    ports:
    - 1025:1025
    - 8025:8025

  dm-db:
    image: postgres:latest
    environment:
      - POSTGRES_NAME=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: dm-db

  dm-api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=dm-db
      - DB_PORT=5435
      - DB_NAME=test
      - DB_USER=test
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - redis 
      - dm-db
      - mailhog
    container_name: dm-api
  
volumes:
  pgdata:
