version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    container_name: dailymotion_redis
    
  mailhog:
    image: mailhog/mailhog
    ports:
    - 1025:1025
    - 8025:8025
    container_name: dailymotion_mailserver

  db:
    image: postgres:latest
    environment:
      - POSTGRES_NAME=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: dailymotion_db

  api:
    build:
      context: .
    ports:
      - "8090:8000"
    environment:
      - DB_HOST=dailymotion_db
      - DB_PORT=5432
      - DB_NAME=test
      - DB_USER=test
      - DB_PASSWORD=test
      - REDIS_HOST=dailymotion_redis 
      - REDIS_PORT=6379
      - SMTP_HOST=dailymotion_mailserver
      - SMTP_PORT=1025
    depends_on:
      - redis 
      - db
      - mailhog
    container_name: dailymotion_api
  
volumes:
  pgdata:
